version: '3'
services:
  db:
    image: mongo:rc
  web:
    build: .
    command: npm run start
    container_name: mozitest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db